# Generated by Django 3.0.7 on 2020-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200808_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_mapping',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity_mapping',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
